name: fan_react
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  shared_preferences: ^2.5.3
  lottie: ^3.2.0
  flutter_svg: ^2.1.0
  percent_indicator: ^4.2.5
  internet_connection_checker_plus: ^2.7.2
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_smart_dialog: ^4.9.8+9
  sliding_up_panel: ^2.0.0+1
  infinite_scroll_pagination: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/json/

  fonts:
    - family: Teachers
      fonts:
        - asset: fonts/Teachers-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Teachers-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Teachers-Medium.ttf
          weight: 500
          style: normal